- hosts: fedora_vms
  become: yes
  tasks:
    - name: Update package manager cache
      dnf:
        update_cache: yes

    - name: Upgrade all installed packages
      dnf:
        name: '*'
        state: latest

    - name: Reboot the host
      reboot:
        msg: "Reboot initiated by Ansible for package updates"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30